# Generated by Django 4.1.13 on 2025-12-18 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0002_alter_carros_options_alter_carros_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carros',
            options={'verbose_name': 'Carro', 'verbose_name_plural': 'Carro'},
        ),
        migrations.AlterModelTable(
            name='carros',
            table='carro',
        ),
    ]
